version: '3'

services:
 service_discovery_db:
  image: postgres:10.3
  container_name: service_discovery_db
  #ports:
  # - "5432:5432"
  volumes:
   - postgres_data:/var/lib/postgresql/data
  restart: always
  environment:
   POSTGRES_USER: $POSTGRES_USER
   POSTGRES_PASSWORD: $POSTGRES_PASSWORD

 service_discovery_webservice:
  build: .
  container_name: service_discovery_webservice
  ports:
   - "5000:5000"
   - "4840:4840"
  restart: always

volumes:
 postgres_data:
